# Generated by Django 3.1.5 on 2021-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name storage.', max_length=100, verbose_name='Storage')),
                ('url', models.URLField(help_text='URL API.', verbose_name='URL')),
                ('api_key', models.CharField(help_text='API Key of storage.', max_length=20, unique=True, verbose_name='API KEY')),
            ],
        ),
    ]
